disabled_rules:
  - function_body_length
  - file_length
  - large_tuple
  - closure_parameter_position
  - trailing_comma
  - todo
  - function_parameter_count
  - trailing_whitespace
  - operator_whitespace
  - nesting
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
    #  - explicit_acl
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
    # - function_default_parameter_at_end #(test warning)
  - joined_default_parameter #(test)
  - let_var_whitespace
  - literal_expression_end_indentation #(test)
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords #(test)
  - prefixed_toplevel_constant #(test)
  - prohibited_super_call
  - sorted_first_last
  - unavailable_function #(test)
  - unneeded_parentheses_in_closure_argument #(test)
  - vertical_parameter_alignment_on_call
  - yoda_condition

included:
  - Sources
  - Tests

force_cast: error
force_try: error
unavailable_function: error
cyclomatic_complexity:
  warning: 10
  error: 35
  ignores_case_statements: true
line_length:
  error: 120
type_body_length:
  warning: 10000
  error: 100000
shorthand_operator: error
generic_type_name:
  min_length: 0
  max_length: 1000
  allowed_symbols:
  validates_start_with_lowercase: true
type_name:
  min_length: 0
  max_length: 1000
  validates_start_with_lowercase: true
identifier_name:
  min_length: 0
  max_length: 1000
  validates_start_with_lowercase: true
empty_enum_arguments: error
unneeded_break_in_switch: error
modifier_order:
  severity: error
switch_case_alignment:
  severity: error
  indented_case: true
closing_brace: error
colon:
  severity: error
implicit_getter: error
weak_delegate: error
statement_position:
  severity: error
leading_whitespace: error
trailing_newline: error
vertical_parameter_alignment: error
redundant_optional_initialization: error
vertical_whitespace:
  severity: error
trailing_semicolon: error
mark: error
opening_brace: error
unused_optional_binding:
  severity: error
void_return: error
private_over_fileprivate:
  severity: error
  validate_extensions: true
block_based_kvo: error
return_arrow_whitespace: error
syntactic_sugar: error
redundant_string_enum_value: error
legacy_constructor: error
comma: error
multiple_closures_with_trailing_closure: error
unused_closure_parameter: error
unused_enumerated: error
for_where: error
control_statement: error

# Opt-ins:
attributes:
  severity: error
closure_end_indentation: error
closure_spacing: error
contains_over_first_not_nil: error
discouraged_object_literal: error
empty_count: error
empty_string: error
#explicit_acl: error
explicit_init: error
fallthrough: error
fatal_error_message: error
first_where: error
# not available yet: function_default_parameter_at_end: error #(test warning)
joined_default_parameter: error #(test)
let_var_whitespace: error
literal_expression_end_indentation: error #(test)
# not available yet: modifier_order: error
operator_usage_whitespace: error
overridden_super_call:
  severity: error
pattern_matching_keywords: error #(test)
prefixed_toplevel_constant:
  severity: error #(test)
prohibited_super_call:
  severity: error
sorted_first_last: error
# not available yet: unavailable_function: error #(test)
unneeded_parentheses_in_closure_argument: error #(test)
vertical_parameter_alignment_on_call: error
yoda_condition: error
