version: 2.1

parameters:
  job:
    type: string
    default: "test"
  deploy_type:
    type: string
    default: ""
  options:
    type: string
    default: ""

jobs:
  test:
    docker:
      - image: norionomura/swift:swift-4.2-branch
    steps:
      - checkout
      - run: swift test --parallel
  deploy:
    docker:
      - image: docker:latest
    steps:
      - run: 
          name: Install Dependencies
          command: apk add --update --no-cache openssh-client make
      - run:
          name: Fix Host Authenticity
          command: 
            mkdir ~/.ssh && ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - checkout
      - setup_remote_docker
      - run: 
          name: Build & Export & Scp & Deploy
          command: |
            make build-export-scp-deploy

workflows:
  version: 2

  test:
    when:
      equal: [ test, << pipeline.parameters.job >> ]
    jobs:
      - test

  deploy:
    when:
      equal: [ deploy, << pipeline.parameters.job >> ]
    jobs:
      - deploy