version: 2

jobs:
  test:
    docker:
      - image: norionomura/swift:swift-4.1-branch
    steps:
      - checkout
      - run: swift test
  deploy:
    docker:
      - image: docker:latest
    steps:
      - run: 
          name: Install Dependencies
          command: apk add --update --no-cache openssh-client
      - run:
          name: Fix Host Authenticity
          command: 
            ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - checkout
      - setup_remote_docker
      - run: 
          command: |
            make build-export-scp-deploy SSH_USER=$SSH_USER SSH_HOST=$SSH_HOST SSH_PATH=$SSH_PATH CIRCLECITOKENS=$CIRCLECITOKENS SLACKTOKEN=$SLACKTOKEN PORT=$PORT VCS=$VCS PROJECTS=$PROJECTS COMPANY=$COMPANY SUDO=$SUDO

workflows:
  version: 2
  tests:
    jobs:
      - test:
          filters:
            branches:
              only:
                - dev
                - master
                - release

