version: 2

jobs:
  test:
    docker:
      - image: norionomura/swift:swift-4.2-branch
    steps:
      - checkout
      - run: swift test --parallel
  deploy:
    docker:
      - image: docker:latest
    steps:
      - run: 
          name: Install Dependencies
          command: apk add --update --no-cache openssh-client make
      - run:
          name: Fix Host Authenticity
          command: 
            mkdir ~/.ssh && ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - checkout
      - setup_remote_docker
      - run: 
          name: Build & Export & Scp & Deploy
          command: |
            make build-export-scp-deploy

workflows:
  version: 2
  tests:
    jobs:
      - test:
          filters:
            branches:
              only:
                - dev
                - master
                - release

