version: 2

jobs:
  test:
    docker:
      - image: norionomura/swift:swift-4.1-branch
    steps:
      - checkout
      - run: swift test
workflows:
  version: 2
  tests:
    jobs:
      - test:
          filters:
            branches:
              only:
                - dev
                - master
                - release

