version: 2

jobs:
  build:
    docker:
      - image: norionomura/swift:swift-4.1-branch
    steps:
      - checkout
#      - run: apt-get update
#      - run: apt-get install -yq libssl-dev pkg-config
#      - run: swift build
      - run: swift test
workflows:
  version: 2
  tests:
    jobs:
      - build
